FROM ubuntu:16.04
WORKDIR /root/

RUN apt-get update
RUN apt-get install git python3-pip curl vim -y
RUN pip3 install --upgrade pip

RUN git clone git://github.com/inducer/relate
WORKDIR /root/relate
RUN cp local_settings_example.py local_settings.py
RUN pip3 install -r requirements.txt
ADD local_settings.py /root/relate/
RUN python3 manage.py migrate
#RUN python3 manage.py createsuperuser --username=admin

RUN apt-get install -y npm
RUN npm install
CMD ["python3","manage.py","runserver","0.0.0.0:8000"]
