---
# Source: relate/templates/relate-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-relate
  labels:
    volume: relate
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/var/opt/relate"

---
# Source: relate/templates/relate-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-relate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      volume: relate

---
# Source: relate/templates/relate-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: relate-service
spec:
  type: ClusterIP
  ports:
  - name: relate
    port: 80
    targetPort: 7777
    protocol: TCP
  selector:
    app: relate

---
apiVersion: v1
kind: Service
metadata:
  name: relate-documentation-service
spec:
  type: ClusterIP
  ports:
  - name: relate-doc
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: relate-doc

---
apiVersion: v1
kind: Service
metadata:
  name: relate-staticfile-service
spec:
  type: ClusterIP
  ports:
  - name: relate-static
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: relate-static

---
# Source: relate/templates/relate-deployment.yaml
apiVersion: v1
kind: Pod
metadata:
  name: relate
  labels:
    app: relate
spec:
  containers:
  - name: relate
    image: relate-webui:20180818007
    ports:
    - name: relate
      containerPort: 7777
      protocol: TCP
    volumeMounts:
    - mountPath: "/var"
      name: pvc-relate
    env:
    - name: DEPLOYMENT_ENV
      value: staging
  volumes:
    - name: pvc-relate
      persistentVolumeClaim:
       claimName: pvc-relate

---
apiVersion: v1
kind: Pod
metadata:
  name: relate-doc
  labels:
    app: relate-doc
spec:
  containers:
  - name: relate-doc
    image: relate-documentation-server:20180528
    ports:
    - name: relate-doc
      containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: relate-static
  labels:
    app: relate-static
spec:
  containers:
  - name: relate-static
    image: relate-staticfiles-webserver:20180524
    ports:
    - name: relate-static
      containerPort: 80
      protocol: TCP


