apiVersion: v1
kind: Pod
metadata:
  name: relate
  labels:
    app: relate
spec:
  containers:
  - name: relate
    image: relate-webui:20180823006
    ports:
    - name: relate
      containerPort: 7777
      protocol: TCP
    volumeMounts:
    - mountPath: "/var"
      name: pvc-relate
    env:
    - name: DEPLOYMENT_ENV
      value: staging
  volumes:
    - name: pvc-relate
      persistentVolumeClaim:
       claimName: pvc-relate

---
apiVersion: v1
kind: Pod
metadata:
  name: relate-doc
  labels:
    app: relate-doc
spec:
  containers:
  - name: relate-doc
    image: relate-documentation-server:20180528
    ports:
    - name: relate-doc
      containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: relate-static
  labels:
    app: relate-static
spec:
  containers:
  - name: relate-static
    image: relate-staticfiles-webserver:20180524
    ports:
    - name: relate-static
      containerPort: 80
      protocol: TCP

