apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-relate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      volume: relate
