apiVersion: v1
kind: Service
metadata:
  name: relate-service
spec:
  type: ClusterIP
  ports:
  - name: relate
    port: 80
    targetPort: 7777
    protocol: TCP
  selector:
    app: relate

---
apiVersion: v1
kind: Service
metadata:
  name: relate-documentation-service
spec:
  type: ClusterIP
  ports:
  - name: relate-doc
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: relate-doc

---
apiVersion: v1
kind: Service
metadata:
  name: relate-staticfile-service
spec:
  type: ClusterIP
  ports:
  - name: relate-static
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: relate-static
