apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-relate
  labels:
    volume: relate
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/var/opt/relate"
